name: dio_api_client
description: API Client for flutter projects based on dio package.
version: 1.0.0
homepage: https://mohesu.com
repository: https://github.com/mohesu/dio_api_client

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  pretty_dio_logger: ^1.3.1
  logger: ^1.4.0
  path_provider: ^2.0.15
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
