name: dio_api_client
description: API Client for flutter projects based on dio package. It supports caching, logging, authentication, error handling, etc. It is easy to use and extend.
version: 1.0.2
homepage: https://mohesu.com
repository: https://github.com/mohesu/dio_api_client

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  dio: ^5.2.1+1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  pretty_dio_logger: ^1.3.1
  logger: ^1.4.0
  path_provider: ^2.0.15
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.1.1
